namespace AHI.Device.Function.Constant
{
    public static class DescriptionMessage
    {
        public const string INGEST_START = "AUDIT.LOG.DESCRIPTION.INGEST_START";
        public const string INGEST_SUCCESS = "AUDIT.LOG.DESCRIPTION.INGEST_SUCCESS";
        public const string INGEST_FAIL = "AUDIT.LOG.DESCRIPTION.INGEST_FAIL";
        public const string DEVICE_FILE_INGESTION_DEVICEID_NOT_EXIST = "AUDIT.LOG.INGESTION_ERROR.DEVICEID_NOT_EXIST.";
        public const string DEVICE_FILE_INGESTION_INVALID_DATA_TYPE = "AUDIT.LOG.INGESTION_ERROR.INVALID_DATA_TYPE.";
        public const string DEVICE_FILE_INGESTION_INVALID_TIMESTAMP = "AUDIT.LOG.INGESTION_ERROR.INVALID_TIMESTAMP.";
        public const string DEVICE_FILE_INGESTION_INVALID_FORMAT = "AUDIT.LOG.INGESTION_ERROR.INVALID_FORMAT.";
        public const string DEVICE_FILE_INGESTION_INVALID_CSV_FORMAT = "AUDIT.LOG.INGESTION_ERROR.INVALID_CSV_FORMAT.";
    }
}
