version: "3"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-CU16-ubuntu-20.04"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pass1234!"
      ACCEPT_EULA: "Y"
      MSSQL_DB: Reporting
    networks:
      - docker_backend
  postgresdb:
    image: "dxpprivate.azurecr.io/timescaledb-ha:latest"
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=250'
    environment:
      POSTGRES_PASSWORD: "Pass1234!"
    networks:
      - docker_backend
  redis:
    image: redis:6.2.6-alpine
    command: redis-server --requirepass Pass1234!
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
    restart: on-failure
    ports:
      - "6379:6379"
    # depends_on:
    #   - db
    #   - idp
    networks:
      - docker_backend
networks:
  docker_backend: # important, https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects
    external: true
