# These ARGs allow for swapping out the base used to make the final image when debugging from VS
ARG LAUNCHING_FROM_VS
# This sets the base image for final, but only if LAUNCHING_FROM_VS has been defined
ARG FINAL_BASE_IMAGE=${LAUNCHING_FROM_VS:+aotdebug}

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
# Install clang/zlib1g-dev dependencies for publishing to native
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    clang zlib1g-dev
ARG BUILD_CONFIGURATION=Release
WORKDIR .
COPY NuGet.Config ./NuGet.Config
COPY device-consumer-kraftshared/*.csproj ./device-consumer-kraftshared/
COPY device-consumer-kraft/*.csproj ./device-consumer-kraft/
RUN dotnet restore ./device-consumer-kraft/*.csproj /property:Configuration=Release -nowarn:msb3202,nu1503

COPY device-consumer-kraft/ ./device-consumer-kraft/
COPY device-consumer-kraftshared/ ./device-consumer-kraftshared/
RUN dotnet publish device-consumer-kraft/*.csproj -c Release -o /app/out /p:UseAppHost=true

FROM base as aotdebug
USER root
# Install GDB to support native debugging
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    gdb
USER app

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM ${FINAL_BASE_IMAGE:-mcr.microsoft.com/dotnet/runtime-deps:8.0} AS final
WORKDIR /app
EXPOSE 8080
EXPOSE 8081
COPY --from=build /app/out .
ENTRYPOINT ["./Device.Consumer.Kraft"]
