-- Because the script 2021-12_28_001_insert_uom.sql is not reuseable, updating it will break the asset template and asset (ref uom)


CREATE TEMPORARY TABLE temp_uom_ids(
   id int
);
INSERT INTO temp_uom_ids (id)

SELECT id FROM uoms where name in (
    'count',
    'coulomb',
    'Ampere hour',
    'kilogram per second',
    'long ton per day',
    'million pound per day',
    'short ton per day',
    'thousand pound per day',
    'gram per second',
    'pound per second',
    'tonne per day',
    'gram',
    'milligram',
    'pound',
    'tonne',
    'long ton',
    'million pound',
    'ounce',
    'short ton',
    'thousand pound',
    'ton',
    'kilogram',
    'second',
    'hour',
    'month',
    'week',
    'year',
    'day',
    'minute',
    'dyne',
    'kilogram-force',
    'pound-force',
    'newton',
    'million British thermal unit per day',
    'million British thermal unit per hour',
    'watt',
    'gigawatt',
    'megawatt',
    'British thermal unit per hour',
    'calorie per second',
    'horsepower',
    'joule per second',
    'kilowatt',
    'megajoule per hour',
    'million calorie per hour',
    'mole per second',
    'gram mole per second',
    'kilogram mole per second',
    'pound mole per second',
    'meter',
    'centimeter',
    'inch',
    'International nautical mile',
    'kilometer',
    'millimeter',
    'foot',
    'mile',
    'sixteenth of an inch',
    'yard',
    'candela',
    'meter per second',
    'centimeter per second',
    'foot per second',
    'International nautical mile per hour',
    'kilometer per hour',
    'mile per hour',
    'revolution per minute',
    'radian per second',
    'British thermal unit per degree Rankine',
    'British thermal unit per degree Fahrenheit',
    'kilojoule per kelvin',
    'joule per kelvin',
    'cubic meter per second',
    'barrel per day',
    'cubic centimeter per second',
    'cubic foot per second',
    'cubic meter per hour',
    'Imperial gallon per minute',
    'liter per second',
    'US gallon per minute',
    'pascal',
    'atmosphere',
    'bar',
    'inches of mercury',
    'kilogram-force per square centimeter',
    'kilogram-force per square meter',
    'kilopascal',
    'millimeter of mercury',
    'newton per square meter',
    'pound-force per square inch',
    'pound-force per square inch (customary)',
    'torr',
    'square meter',
    'hectare',
    'square centimeter',
    'square inch',
    'square kilometer',
    'square millimeter',
    'square foot',
    'acre',
    'square mile',
    'square yard',
    'degree Celsius',
    'degree Rankine',
    'degree Fahrenheit',
    'kelvin',
    'milliampere',
    'ampere',
    'joule per kilogram',
    'joule per gram',
    'British thermal unit per pound',
    'kilocalorie per kilogram',
    'kilojoule per kilogram',
    'kilojoule per pound',
    'hertz',
    'British thermal unit per pound degree Rankine',
    'British thermal unit per pound degree Fahrenheit',
    'joule per gram kelvin',
    'kilojoule per kilogram kelvin',
    'joule per kilogram kelvin',
    'mole',
    'gram mole',
    'kilogram mole',
    'pound mole',
    'parts per billion',
    'parts per million',
    'percent',
    'kilogram per mole',
    'gram per gram mole',
    'pound per pound mole',
    'kilogram per kilogram mole',
    'volt',
    'kilovolt',
    'megavolt',
    'gigawatt hour',
    'megawatt hour',
    'watt hour',
    'joule',
    'British thermal unit',
    'calorie',
    'gigajoule',
    'kilojoule',
    'kilowatt hour',
    'megajoule',
    'watt second',
    'kilocalorie',
    'million calorie',
    'million British thermal unit',
    'million imperial gallon',
    'thousand imperial gallon',
    'barrel',
    'Imperial gallon',
    'million US gallon',
    'thousand US gallon',
    'cubic centimeter',
    'cubic foot',
    'kiloliter',
    'liter',
    'megaliter',
    'milliliter',
    'thousand cubic meter',
    'US gallon',
    'million barrel',
    'thousand barrel',
    'acre foot',
    'cubic meter',
    'ohm',
    'kilogram per cubic meter',
    'gram per liter',
    'kilogram per liter',
    'pound per barrel',
    'pound per cubic foot',
    'pound per US gallon',
    'tonne per cubic meter',
    'radian',
    'degree',
    'revolution',
    'pascal second',
    'poise',
    'cubic foot per pound',
    'cubic centimeter per gram',
    'cubic meter per kilogram',
    'delta kelvin',
    'delta degree Fahrenheit',
    'delta degree Rankine',
    'delta degree Celsius'
);

UPDATE uoms SET system = true WHERE id IN (SELECT id FROM temp_uom_ids);

DROP TABLE temp_uom_ids;
