version: "3"
services:
  storage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "10000:10000"
      - "10001:10001"
    networks:
      - backend
  rabbitmq:
    image: "rabbitmq:3.10.2-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "Pass1234!"
    volumes:
      - ../rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ../rabbitmq/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - backend