namespace Device.Application.Constant
{
    public static class MessageConstants
    {
        public const string INVALID_PERMISSION = "INVALID_PERMISSION";
        public const string ATTRIBUTE_VALUE_OVERFLOW = "ERROR.ENTITY.INVALID.ATTRIBUTE_VALUE_OVERFLOW";

        //asset
        public const string ASSET_NOT_FOUND = "ERROR.ENTITY.NOT_FOUND.ASSET.NOT_FOUND";
        public const string ASSET_USING = "ERROR.ENTITY.INVALID.ASSET.USING";
        public const string ASSET_ATTRIBUTE_NOT_FOUND = "ERROR.ENTITY.NOT_FOUND.ASSET.ATTRIBUTE_NOT_FOUND";
        public const string ASSET_TEMPLATE_DECORATED_ATTRIBUTE_INVALID = "ERROR.ENTITY.INVALID.ASSET.DECORATED_ATTRIBUTE_INVALID";
        public const string ASSET_ATTRIBUTE_RUNTIME_USED_EXPRESSION = "ERROR.ENTITY.INVALID.ASSET.ATTRIBUTE_RUNTIME_USED_EXPRESSION";
        public const string ASSET_ATTRIBUTE_MAPPING_INVALID = "ERROR.GENERIC.COMMON_EXCEPTION.ASSET.ATTRIBUTE_ID_NOT_FOUND";
        public const string ASSET_ATTRIBUTE_TYPE_INVALID = "ERROR.SYSTEM.NOT_SUPPORTED.ASSET.ATTRIBUTE_TYPE_INVALID";
        public const string ASSET_ATTRIBUTE_USING = "ERROR.ENTITY.INVALID.ASSET.ATTRIBUTE_USING";
        public const string ASSET_ATTRIBUTE_HAVE_REFERENCE = "ERROR.ENTITY.INVALID.ASSET.ATTRIBUTE_HAVE_REFERENCE";
        public const string ASSET_HAS_CHILD_ASSET = "ERROR.ENTITY.INVALID.ASSET.HAS_CHILD_ASSET";
        public const string ASSET_PARENT_UNSAVED = "ERROR.ENTITY.NOT_FOUND.ASSET.PARENT_UNSAVED";
        public const string ASSET_MEDIA_MOVE_TO_CHANGED_MEDIA = "ERROR.ENTITY.INVALID.ASSET_MEDIA.MOVE_TO_CHANGED_MEDIA";
        public const string ASSET_MEDIA_MOVE_TO_SUBFOLDER = "ERROR.ENTITY.INVALID.ASSET_MEDIA.MOVE_TO_SUBFOLDER";
        public const string ASSET_TABLE_TIMESTAMP_INVALID = "ERROR.GENERIC.COMMON_EXCEPTION.ASSET_TABLE.TIME_STAMP_INVALID";
        public const string ASSET_CLONE_ASSET_NAME_MAX_LENGTH = "ERROR.ENTITY.INVALID.CLONE_ASSET_NAME_MAX_LENGTH";
        public const string ASSET_CREATE_ASSET_TEMPLATE_NAME_MAX_LENGTH = "ERROR.ENTITY.INVALID.CREATE_ASSET_TEMPLATE_NAME_MAX_LENGTH";
        public const string ASSET_ATTRIBUTE_NAME_ALREADY_EXISTS = "ERROR.ENTITY.INVALID.ASSET_ATTRIBUTE_HAS_SAME_NAME_AS_TEMPLATE_ATTRIBUTE";
        public const string ASSET_ALIAS_CIRCULAR_REFERENCE = "ERROR.ENTITY.INVALID.ASSET_ALIAS.CIRCULAR_REFERENCE";
        public const string ASSET_MAPPING_DEVICE_INSTANCE_INVALID = "ERROR.ENTITY.VALIDATION.ASSET_MAPPING.DEVICE_INSTANCE_INVALID";

        //device_template
        public const string DEVICE_TEMPLATE_NOT_FOUND = "ERROR.ENTITY.NOT_FOUND.DEVICE_TEMPLATE.NOT_FOUND";
        public const string DEVICE_TEMPLATE_USING = "ERROR.ENTITY.INVALID.DEVICE_TEMPLATE.USING";
        public const string DEVICE_TEMPLATE_PAYLOAD_USING = "ERROR.ENTITY.INVALID.DEVICE_TEMPLATE.PAYLOAD_USING";
        public const string DEVICE_TEMPLATE_METRIC_USING = "ERROR.ENTITY.INVALID.DEVICE_TEMPLATE.METRIC_USING";
        public const string DEVICE_TEMPLATE_NOT_BINDING = "ERROR.ENTITY.INVALID.DEVICE_TEMPLATE.NOT_BINDING";
        public const string DEVICE_TEMPLATE_BINDING_USING = "ERROR.ENTITY.INVALID.DEVICE_TEMPLATE.BINDING_USING";
        public const string DEVICE_TEMPLATE_PAYLOAD_METRIC_USING_EXPRESSION = "ERROR.ENTITY.INVALID.DEVICE_TEMPLATE.PAYLOAD_METRIC_USING_EXPRESSION";

        //asset template
        public const string ASSET_TEMPLATE_USING = "ERROR.ENTITY.INVALID.ASSET_TEMPLATE.USING";
        public const string ASSET_TEMPLATE_ATTRIBUTE_TYPE_INVALID = "ERROR.SYSTEM.NOT_SUPPORTED.ASSET_TEMPLATE.ATTRIBUTE_TYPE_INVALID";

        //device
        public const string DEVICE_NOT_FOUND = "ERROR.ENTITY.NOT_FOUND.DEVICE.NOT_FOUND";
        public const string DEVICE_USING = "ERROR.ENTITY.INVALID.DEVICE.USING";
        public const string DEVICE_GENERATE_PRIMARY_FAILED = "ERROR.ENTITY.INVALID.DEVICE.GENERATE_PRIMARY_KEY_FAILED";
        public const string DEVICE_PRIMARY_KEY_INVALID = "ERROR.ENTITY.INVALID.DEVICE.PRIMARY_KEY_INVALID";
        public const string DEVICE_OPTION_SEND_IS_DISABLE = "ERROR.ENTITY.INVALID.DEVICE.OPTION_SEND_DISABLE";

        // public const string DEVICE_SECONDARY_KEY_INVALID = "DEVICE.SECONDARY_KEY_INVALID";
        public const string DEVICE_IOT_HUB_NOT_VALID = "ERROR.ENTITY.INVALID.DEVICE.IOT_HUB_NOT_VALID";
        public const string DEVICE_BROKER_NOT_SUPPORTED = "ERROR.ENTITY.INVALID.DEVICE.BROKER_NOT_SUPPORTED";
        public const string DEVICE_IOT_HUB_NOT_FOUND = "ERROR.ENTITY.NOT_FOUND.DEVICE.IOT_HUB_INACTIVE_OR_DELETED";
        public const string SEND_MESSAGE_BASIC_TIER_NOT_SUPPORTED = "ERROR.ENTITY.INVALID.DEVICE.BASIC_TIER_NOT_SUPPORTED";
        public const string DETAIL_CODE_DEVICE_RELATED_ITEMS_DELETED_OR_INACTIVATED = "ERROR.ENTITY.VALIDATION.SOME_ITEMS_DELETED_OR_INACTIVATED";
        public const string DETAIL_CODE_DEVICE_CANNOT_UPDATE_ID_AND_RETENTIONSDAYS = "DETAIL_CODE_DEVICE_CANNOT_UPDATE_ID_AND_RETENTIONSDAYS";
        public const string ERROR_CODE_DEVICE_RELATED_ITEMS_DELETED_OR_INACTIVATED = "ERROR.ENTITY.VALIDATION.FIELD_DELETED_OR_INACTIVATED";
        public const string DEVICE_IDENTIFIER_EXIST_IN_BROKER = "ERROR.ENTITY.VALIDATION.IDENTIFIER_EXIST_IN_BROKER";
        public const string DEVICE_ID_UNMATCHED_BROKER_TYPE = "ERROR.ENTITY.VALIDATION.ID_UNMATCHED_BROKER_TYPE";
        public const string DEVICE_ID_UNMATCHED_BROKER_TYPE_LOG = "ERROR.ENTITY.VALIDATION.ID_UNMATCHED_BROKER_TYPE_LOG";

        // uom
        public const string UOM_USING = "ERROR.ENTITY.INVALID.UOM.USING";
        public const string UOM_CIRCULAR_REFERENCE = "ERROR.ENTITY.INVALID.UOM.CIRCULAR_REFERENCE";

        // block function
        public const string BLOCK_FUNCTION_HAS_BEEN_PUBLISHED = "ERROR.ENTITY.INVALID.BLOCK_FUNCTION_HAS_BEEN_PUBLISHED";
        public const string BLOCK_FUNCTION_TRIGGER_TYPE_INVALID = "ERROR.SYSTEM.NOT_SUPPORTED.BLOCK_FUNCTION_TRIGGER_TYPE_INVALID";
        public const string BLOCK_FUNCTION_OPERATION_NOT_SUPPORTED = "ERROR.SYSTEM.NOT_SUPPORTED.BLOCK_FUNCTION_OPERATION_NOT_SUPPORTED";
        public const string FILTER_UNIT_NOT_SUPPORTED = "ERROR.SYSTEM.NOT_SUPPORTED.FILTER_UNIT_NOT_SUPPORTED";
        public const string DATA_TYPE_NOT_SUPPORTED = "ERROR.SYSTEM.NOT_SUPPORTED.DATA_TYPE_NOT_SUPPORTED";
        public const string BINDING_IS_BEING_USED = "ERROR.ENTITY.INVALID.BINDING_IS_BEING_USED";
        public const string BLOCK_IS_BEING_USED = "ERROR.ENTITY.INVALID.BLOCK_IS_BEING_USED";
        public const string BLOCK_TEMPLATE_IS_BEING_USED = "ERROR.ENTITY.INVALID.BLOCK_TEMPLATE_IS_BEING_USED";
        public const string BLOCK_CATEGORY_HAS_CHILD = "ERROR.ENTITY.INVALID.BLOCK_CATEGORY.HAS_CHILD";
        public const string BLOCK_FUNCTION_CLONE_NAME_MAX_LENGTH = "ERROR.ENTITY.INVALID.CLONE_FUNCTION_BLOCK_NAME_MAX_LENGTH";
        public const string BLOCK_FUNCTION_CATEGORY_INVALID = "ERROR.ENTITY.INVALID.BLOCK_CATEGORY.PARENT_ID_INVALID";

        // block execution
        public const string BLOCK_EXECUTION_HAS_ERROR = "ERROR.ENTITY.INVALID.BLOCK_EXECUTION_HAS_ERROR_STATUS";
        public const string BLOCK_EXECUTION_ERROR_CALL_SERVICE = "ERROR.ENTITY.INVALID.BLOCK_EXECUTION.CALL_SERVICE_FAILED";
        public const string BLOCK_EXECUTION_ERROR_REGISTER_EVENT_FORWARDING = "ERROR.ENTITY.VALIDATION.REGISTER_EVENT_FORWARDING";
        public const string BLOCK_EXECUTION_ERROR_REGISTER_SCHEDULER_JOB = "ERROR.ENTITY.VALIDATION.REGISTER_SCHEDULER_JOB";
        public const string BLOCK_EXECUTION_ERROR_CONNECTOR_DELETED = "ERROR.ENTITY.VALIDATION.CONNECTOR_HAS_BEEN_DELETED";
        public const string BLOCK_EXECUTION_ERROR_TRIGGER_DELETED = "ERROR.ENTITY.VALIDATION.TRIGGER_HAS_BEEN_DELETED";

        // DB Exception code
        public const string DATABASE_QUERY_FAILED = "ERROR.DATABASE.QUERY_FAILED";
        public const string DEVICE_SEND_CONFIGURATION_FAIL = "DEVICE.DEVICE_SEND_CONFIGURATION_FAIL";
        public const string DEVICE_IOT_HUB_BROKER_DELETED = "ERROR.ENTITY.NOT_FOUND.DEVICE.BROKER_DELETED";
        public const string BROKER_CONTENT_EMPTY = "BROKER.CONTENT.EMPTY";
        public const string MESSAGE_ASSETS_SAVE_ASSET_LOOP_ALIAS = "MESSAGE.ASSETS.SAVE_ASSET_LOOP_ALIAS";
    }

    public static class MessageDetailConstants
    {
        public const string BROKER_HAS_BEEN_DELETED = "ERROR.API.DEVICE.IOT_HUB_HAS_BEEN_DELETED";
        public const string TIER_IS_NOT_STANDARD = "ERROR.ENTITY.INVALID.DEVICE.BASIC_TIER_NOT_SUPPORTED";
        public const string INVALID_VALUE = "ERROR.ENTITY.VALIDATION.FIELD_INVALID";
        public const string OUT_OF_RANGE_OF_DATA_TYPE = "ERROR.ENTITY.VALIDATION.OUT_OF_RANGE";
        public const string METRIC_DELETED = "ERROR.ENTITY.METRIC_HAS_BEEN_DELETED";
        public const string TOO_MANY_REQUEST = "ERROR.ENTITY.VALIDATION.TOO_MANY_REQUEST";
    }
}
